# Generated by Django 5.1.4 on 2024-12-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_category_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categoryName',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
    ]
